CREATE DATABASE BIDA;
GO

USE BIDA;
GO

CREATE TABLE NHANVIEN (
    MANV VARCHAR(15) NOT NULL,
    HOTEN VARCHAR(50) NOT NULL,
    CHUCVU VARCHAR(20) NOT NULL,
    MATKHAU VARCHAR(15) NOT NULL,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);
GO

CREATE TABLE KHACHHANG (
    MAKH VARCHAR(15) NOT NULL,
    TENKH VARCHAR(50) NOT NULL,
    CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
);
GO

CREATE TABLE BANBIDA (
    MABAN VARCHAR(10) NOT NULL,
    TRANGTHAI INT DEFAULT 0,
    PRICE FLOAT DEFAULT 0,
    CONSTRAINT PK_BANBIDA PRIMARY KEY(MABAN)
);
GO

CREATE TABLE HOADON (
    MAHD VARCHAR(15) NOT NULL,
    MABAN VARCHAR(10) NOT NULL,
    MAKH VARCHAR(15) NOT NULL,
    TIMEIN DATETIME,
    TIMEOU DATETIME,
    CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
    CONSTRAINT FK_HOADON_BANBIDA FOREIGN KEY(MABAN) REFERENCES BANBIDA(MABAN),
    CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
);
GO

CREATE TABLE CTHOADON (
    ID INT IDENTITY PRIMARY KEY,
    MAHD VARCHAR(15) NOT NULL,
    MABAN VARCHAR(10) NOT NULL,
    COUNT INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CTHOADON_BANBIDA FOREIGN KEY(MABAN) REFERENCES BANBIDA(MABAN)
);
GO

CREATE TABLE PHUCVU (
    MANV VARCHAR(15) NOT NULL,
    MABAN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PHUCVU PRIMARY KEY(MANV, MABAN),
    CONSTRAINT FK_PHUCVU_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PHUCVU_BANBIDA FOREIGN KEY(MABAN) REFERENCES BANBIDA(MABAN)
);
GO

DELETE FROM BANBIDA
INSERT INTO BANBIDA
VALUES 
	('BAN1', 0, 40001),
	('BAN2', 0, 40002),
	('BAN3', 0, 40003),
	('BAN4', 0, 40004),
	('BAN5', 0, 40005),
	('BAN6', 0, 40006),
	('BAN7', 0, 40007),
	('BAN8', 0, 40008),
	('BAN9', 0, 40009),
	('BAN10', 0, 40010),
	('BAN11', 0, 40011),
	('BAN12', 0, 40012),
	('BAN2.1', 0, 50001),
	('BAN2.2', 0, 50002),
	('BAN2.3', 0, 50003),
	('BAN2.4', 0, 50004),
	('BAN2.5', 0, 50005),
	('BAN2.6', 0, 50006),
	('BAN2.7', 0, 50007),
	('BAN2.8', 0, 50008),
	('BAN2.9', 0, 50009),
	('BAN2.VIP', 0, 100000);